In [1]:
import pandas as pd

In [2]:
df_del = pd.read_csv(r"C:\Users\65866\Downloads\deliveries.csv")

In [3]:
df_mat = pd.read_csv(r"C:\Users\65866\Downloads\matches.csv")

In [4]:
df_del

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [5]:
df_mat

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [ ]:
merged_df = pd.merge(left_df, right_df, on='key_column', how='inner')

In [6]:
df_del.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [7]:
df_mat.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [8]:
df_mat['city'].value_counts()

Mumbai            101
Kolkata            77
Delhi              74
Bangalore          66
Hyderabad          64
Chennai            57
Jaipur             47
Chandigarh         46
Pune               38
Durban             15
Bengaluru          14
Visakhapatnam      13
Centurion          12
Ahmedabad          12
Rajkot             10
Mohali             10
Indore              9
Dharamsala          9
Johannesburg        8
Cuttack             7
Ranchi              7
Port Elizabeth      7
Cape Town           7
Abu Dhabi           7
Sharjah             6
Raipur              6
Kochi               5
Kanpur              4
Nagpur              3
Kimberley           3
East London         3
Bloemfontein        2
Name: city, dtype: int64

In [16]:
#dfc = df_mat.groupby(['city','season']).max()

C:\Users\65866\AppData\Local\Temp\ipykernel_10212\417632369.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  dfc = df_mat.groupby(['city','season']).max()

In [19]:
#dfc.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [20]:
#dfc

                         id        date                        team1  \
city          season
Abu Dhabi     2014      476  2014-04-29          Sunrisers Hyderabad
Ahmedabad     2010      198  2010-03-28             Rajasthan Royals
              2014      501  2014-05-19          Sunrisers Hyderabad
              2015      540  2015-04-24             Rajasthan Royals
Bangalore     2008      111  2008-05-28  Royal Challengers Bangalore
...                     ...         ...                          ...
Sharjah       2014      474  2014-04-27          Sunrisers Hyderabad
Visakhapatnam 2012      316  2012-04-09              Deccan Chargers
              2015      537  2015-04-22          Sunrisers Hyderabad
              2016      629  2016-05-21          Sunrisers Hyderabad
              2019    11414    10/05/19          Sunrisers Hyderabad

                                            team2  \
city          season
Abu Dhabi     2014               Rajasthan Royals
Ahmedabad     2010               Rajasthan Royals
              2014               Rajasthan Royals
              2015    Royal Challengers Bangalore
Bangalore     2008    Royal Challengers Bangalore
...                                           ...
Sharjah       2014            Sunrisers Hyderabad
Visakhapatnam 2012                 Mumbai Indians
              2015            Sunrisers Hyderabad
              2016        Rising Pune Supergiants
              2019                 Delhi Capitals

                                      toss_winner toss_decision  result  \
city          season
Abu Dhabi     2014               Rajasthan Royals         field     tie
Ahmedabad     2010               Rajasthan Royals         field  normal
              2014               Rajasthan Royals         field  normal
              2015    Royal Challengers Bangalore         field     tie
Bangalore     2008    Royal Challengers Bangalore         field  normal
...                                           ...           ...     ...
Sharjah       2014            Sunrisers Hyderabad         field  normal
Visakhapatnam 2012                Deccan Chargers         field  normal
              2015               Rajasthan Royals         field  normal
              2016            Sunrisers Hyderabad         field  normal
              2019                 Delhi Capitals         field  normal

                      dl_applied  win_by_runs  win_by_wickets  \
city          season
Abu Dhabi     2014             0           93               6
Ahmedabad     2010             0           34               8
              2014             0           62               0
              2015             0            0               9
Bangalore     2008             0          140               9
...                          ...          ...             ...
Sharjah       2014             0           72               8
Visakhapatnam 2012             0           74               5
              2015             1           16               6
              2016             1           85               7
              2019             0            0               6

                                                                  venue
city          season
Abu Dhabi     2014                                 Sheikh Zayed Stadium
Ahmedabad     2010                         Sardar Patel Stadium, Motera
              2014                         Sardar Patel Stadium, Motera
              2015                         Sardar Patel Stadium, Motera
Bangalore     2008                                M Chinnaswamy Stadium
...                                                                 ...
Sharjah       2014                              Sharjah Cricket Stadium
Visakhapatnam 2012    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2015    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2016    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2019                                     ACA-VDCA Stadium

[125 rows x 11 columns]

In [21]:
#dfc('season'=='2014').value_counts()

TypeError: 'DataFrame' object is not callable

In [22]:
df_mat.groupby(['city','season']).max()

C:\Users\65866\AppData\Local\Temp\ipykernel_10212\1284037511.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df_mat.groupby(['city','season']).max()

                         id        date                        team1  \
city          season
Abu Dhabi     2014      476  2014-04-29          Sunrisers Hyderabad
Ahmedabad     2010      198  2010-03-28             Rajasthan Royals
              2014      501  2014-05-19          Sunrisers Hyderabad
              2015      540  2015-04-24             Rajasthan Royals
Bangalore     2008      111  2008-05-28  Royal Challengers Bangalore
...                     ...         ...                          ...
Sharjah       2014      474  2014-04-27          Sunrisers Hyderabad
Visakhapatnam 2012      316  2012-04-09              Deccan Chargers
              2015      537  2015-04-22          Sunrisers Hyderabad
              2016      629  2016-05-21          Sunrisers Hyderabad
              2019    11414    10/05/19          Sunrisers Hyderabad

                                            team2  \
city          season
Abu Dhabi     2014               Rajasthan Royals
Ahmedabad     2010               Rajasthan Royals
              2014               Rajasthan Royals
              2015    Royal Challengers Bangalore
Bangalore     2008    Royal Challengers Bangalore
...                                           ...
Sharjah       2014            Sunrisers Hyderabad
Visakhapatnam 2012                 Mumbai Indians
              2015            Sunrisers Hyderabad
              2016        Rising Pune Supergiants
              2019                 Delhi Capitals

                                      toss_winner toss_decision  result  \
city          season
Abu Dhabi     2014               Rajasthan Royals         field     tie
Ahmedabad     2010               Rajasthan Royals         field  normal
              2014               Rajasthan Royals         field  normal
              2015    Royal Challengers Bangalore         field     tie
Bangalore     2008    Royal Challengers Bangalore         field  normal
...                                           ...           ...     ...
Sharjah       2014            Sunrisers Hyderabad         field  normal
Visakhapatnam 2012                Deccan Chargers         field  normal
              2015               Rajasthan Royals         field  normal
              2016            Sunrisers Hyderabad         field  normal
              2019                 Delhi Capitals         field  normal

                      dl_applied  win_by_runs  win_by_wickets  \
city          season
Abu Dhabi     2014             0           93               6
Ahmedabad     2010             0           34               8
              2014             0           62               0
              2015             0            0               9
Bangalore     2008             0          140               9
...                          ...          ...             ...
Sharjah       2014             0           72               8
Visakhapatnam 2012             0           74               5
              2015             1           16               6
              2016             1           85               7
              2019             0            0               6

                                                                  venue
city          season
Abu Dhabi     2014                                 Sheikh Zayed Stadium
Ahmedabad     2010                         Sardar Patel Stadium, Motera
              2014                         Sardar Patel Stadium, Motera
              2015                         Sardar Patel Stadium, Motera
Bangalore     2008                                M Chinnaswamy Stadium
...                                                                 ...
Sharjah       2014                              Sharjah Cricket Stadium
Visakhapatnam 2012    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2015    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2016    Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
              2019                                     ACA-VDCA Stadium

[125 rows x 11 columns]

In [27]:
df_city = df_mat[(df_mat['season']>=2008) & (df_mat['season']<=2019)]

In [28]:
city_match = df_city.value_counts()

In [31]:
city_match.idxmax()

(7894,
 2018,
 'Mumbai',
 '07/04/18',
 'Mumbai Indians',
 'Chennai Super Kings',
 'Chennai Super Kings',
 'field',
 'normal',
 0,
 'Chennai Super Kings',
 0,
 1,
 'DJ Bravo',
 'Wankhede Stadium',
 'Chris Gaffaney',
 'A Nanda Kishore',
 'Anil Chaudhary')

In [32]:
df_mat

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [35]:
df_mat['season'].value_counts()

2013    76
2012    74
2011    73
2010    60
2014    60
2016    60
2018    60
2019    60
2017    59
2015    59
2008    58
2009    57
Name: season, dtype: int64

In [56]:
#df_mat[df_mat['winner']=='Mumbai Indians'] #& (df_mat['season']=='2011')]
dfmi = df_mat[(df_mat['season']=='2011') & ((df_mat['team1']=='Mumbai Indians') | (df_mat['team2']=='Mumbai Indians'))]

In [60]:
dfmi.value_counts()

Series([], dtype: int64)

In [61]:
dfmiv

Series([], Name: winner, dtype: int64)

In [148]:
mi_matches_2011 = df_mat[(df_mat['season'] == 2011) & ((df_mat['team1'] == 'Mumbai Indians') | (df_mat['team2'] == 'Mumbai Indians'))]

In [149]:
mi_wins_2011 = mi_matches_2011['winner'].value_counts()

In [150]:
mi_wins_2011

Mumbai Indians                 10
Rajasthan Royals                2
Kochi Tuskers Kerala            1
Kings XI Punjab                 1
Deccan Chargers                 1
Royal Challengers Bangalore     1
Name: winner, dtype: int64

In [151]:
mi_matches_2011

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
237,238,2011,Delhi,2011-04-10,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
241,242,2011,Bangalore,2011-04-12,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,SR Tendulkar,M Chinnaswamy Stadium,HDPK Dharmasena,AL Hill,NaN
246,247,2011,Mumbai,2011-04-15,Mumbai Indians,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BB McCullum,Wankhede Stadium,BR Doctrove,PR Reiffel,NaN
253,254,2011,Mumbai,2011-04-20,Pune Warriors,Mumbai Indians,Pune Warriors,bat,normal,0,Mumbai Indians,0,7,MM Patel,Wankhede Stadium,Asad Rauf,AM Saheba,NaN
256,257,2011,Mumbai,2011-04-22,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,8,0,Harbhajan Singh,Wankhede Stadium,Asad Rauf,AM Saheba,NaN
259,260,2011,Hyderabad,2011-04-24,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,normal,0,Mumbai Indians,37,0,SL Malinga,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,AL Hill,NaN
266,267,2011,Jaipur,2011-04-29,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,J Botha,Sawai Mansingh Stadium,Asad Rauf,SK Tarapore,NaN
272,273,2011,Mumbai,2011-05-02,Mumbai Indians,Kings XI Punjab,Kings XI Punjab,field,normal,0,Mumbai Indians,23,0,KA Pollard,Wankhede Stadium,HDPK Dharmasena,PR Reiffel,NaN
276,277,2011,Mumbai,2011-05-04,Mumbai Indians,Pune Warriors,Pune Warriors,field,normal,0,Mumbai Indians,21,0,R Sharma,Dr DY Patil Sports Academy,HDPK Dharmasena,SJA Taufel,NaN
281,282,2011,Mumbai,2011-05-07,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,32,0,AT Rayudu,Wankhede Stadium,K Hariharan,SJA Taufel,NaN
286,287,2011,Chandigarh,2011-05-10,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,76,0,BA Bhatt,"Punjab Cricket Association Stadium, Mohali",SK Tarapore,RJ Tucker,NaN
291,292,2011,Mumbai,2011-05-14,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,normal,0,Deccan Chargers,10,0,A Mishra,Wankhede Stadium,S Ravi,SK Tarapore,NaN
298,299,2011,Mumbai,2011-05-20,Mumbai Indians,Rajasthan Royals,Mumbai Indians,bat,normal,0,Rajasthan Royals,0,10,SR Watson,Wankhede Stadium,RE Koertzen,PR Reiffel,NaN
302,303,2011,Kolkata,2011-05-22,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,5,JEC Franklin,Eden Gardens,SK Tarapore,SJA Taufel,NaN
304,305,2011,Mumbai,2011-05-25,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,MM Patel,Wankhede Stadium,Asad Rauf,SJA Taufel,NaN
305,306,2011,Chennai,2011-05-27,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Royal Challengers Bangalore,43,0,CH Gayle,"MA Chidambaram Stadium, Chepauk",Asad Rauf,SJA Taufel,NaN

In [152]:
mi_wins_2011.max()

10

In [73]:
df_mat['toss_decision'].value_counts(normalize=True)*100

field    61.243386
bat      38.756614
Name: toss_decision, dtype: float64

In [71]:
df_mat['toss_decision'].nunique()

2

In [78]:
dtw = df_mat.groupby(['toss_decision','winner']).value_counts()

In [79]:
dtw.max()

1

In [80]:
dtw

toss_decision  winner               id     season  city       date      team1                  team2                        toss_winner          result  dl_applied  win_by_runs  win_by_wickets  player_of_match  venue                                      umpire1                umpire2                umpire3
bat            Chennai Super Kings  11141  2019    Delhi      26/03/19  Delhi Capitals         Chennai Super Kings          Delhi Capitals       normal  0           0            6               SR Watson        Feroz Shah Kotla Ground                    Marais Erasmus         Nitin Menon            Anil Dandekar      1
                                    11309  2019    Chennai    06/04/19  Chennai Super Kings    Kings XI Punjab              Chennai Super Kings  normal  0           22           0               Harbhajan Singh  M. A. Chidambaram Stadium                  KN Ananthapadmanabhan  Rod Tucker             C Shamshuddin      1
               Delhi Capitals       11344  2019    Delhi      04/05/19  Rajasthan Royals       Delhi Capitals               Rajasthan Royals     normal  0           0            5               A Mishra         Feroz Shah Kotla Ground                    Ian Gould              Anil Dandekar          Nitin Menon        1
                                    11337  2019    Delhi      28/04/19  Delhi Capitals         Royal Challengers Bangalore  Delhi Capitals       normal  0           16           0               S Dhawan         Feroz Shah Kotla Ground                    Bruce Oxenford         KN Ananthapadmanabhan  C Shamshuddin      1
               Delhi Daredevils     7948   2018    Delhi      20/05/18  Delhi Daredevils       Mumbai Indians               Delhi Daredevils     normal  0           11           0               A Mishra         Feroz Shah Kotla                           Kumar Dharmasena       O Nandan               Vineet Kulkarni    1
                                                                                                                                                                                                                                                                                                                              ..
field          Sunrisers Hyderabad  7916   2018    Mumbai     24/04/18  Sunrisers Hyderabad    Mumbai Indians               Mumbai Indians       normal  0           31           0               Rashid Khan      Wankhede Stadium                           C Shamshuddin          S Ravi                 A.D Deshmukh       1
                                    7903   2018    Kolkata    14/04/18  Kolkata Knight Riders  Sunrisers Hyderabad          Sunrisers Hyderabad  normal  0           0            5               B Stanlake       Eden Gardens                               A Nanda Kishore        Anil Chaudhary         Chris Gaffaney     1
                                    7900   2018    Hyderabad  12/04/18  Mumbai Indians         Sunrisers Hyderabad          Sunrisers Hyderabad  normal  0           0            1               Rashid Khan      Rajiv Gandhi International Stadium, Uppal  O Nandan               Nigel Llong            Vineet Kulkarni    1
                                    7897   2018    Hyderabad  09/04/18  Rajasthan Royals       Sunrisers Hyderabad          Sunrisers Hyderabad  normal  0           0            9               S Dhawan         Rajiv Gandhi International Stadium, Uppal  Nigel Llong            Vineet Kulkarni        O Nandan           1
                                    11339  2019    Hyderabad  29/04/19  Sunrisers Hyderabad    Kings XI Punjab              Kings XI Punjab      normal  0           45           0               DA Warner        Rajiv Gandhi Intl. Cricket Stadium         S Ravi                 O Nandan               Nanda Kishore      1
Length: 118, dtype: int64

In [81]:
df_mat

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [137]:
batsec_wins = df_mat[df_mat['win_by_wickets'].notnull()]

In [138]:
batsec_wins

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [139]:
yearwins = batsec_wins.groupby('season')['winner'].count()

In [140]:
yearwins

season
2008    58
2009    57
2010    60
2011    72
2012    74
2013    76
2014    60
2015    57
2016    60
2017    59
2018    60
2019    59
Name: winner, dtype: int64

In [84]:
max_wins_years = yearly_wins[yearly_wins == yearly_wins.max()].index

In [85]:
max_wins_years

Int64Index([2013], dtype='int64', name='season')

In [ ]:
# In 2019 which batsman scored highest number of runs by hitting 6's and 4's?

In [ ]:
(df_mat['season']=='2019') & df_mat['']

In [86]:
df_del

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [87]:
runs_2019 = df_del[df_del['season'] == 2019]

KeyError: 'season'

In [90]:
df_del['bowler'].value_counts() #12. Most number of wickets taken by a bowler is

Harbhajan Singh     3451
A Mishra            3172
PP Chawla           3157
R Ashwin            3016
SL Malinga          2974
                    ...
Y Gnaneswara Rao       6
P Prasanth             6
SPD Smith              2
SN Khan                2
AC Gilchrist           1
Name: bowler, Length: 405, dtype: int64

In [166]:
df_del.groupby("bowler")["dismissal_kind"]

In [98]:
bvk = df_del[(df_del['batsman']=='V Kohli') & (df_mat['season']=='2016')]

In [100]:
bvk['total_runs'].sum()

0

In [91]:
df_mat

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [ ]:
#13.  What is the strike rate of Kohli in 2016

In [103]:
# 14.Bowlers with maximum number of extras:
df_del

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [114]:
pd.crosstab(df_del['bowler'],df_del['extra_runs'])

extra_runs         0    1  2  3  4  5  7
bowler
A Ashish Reddy   258   11  0  1  0  0  0
A Chandila       232    1  1  0  0  0  0
A Choudhary      101    7  0  0  0  0  0
A Dananjaya       24    1  0  0  0  0  0
A Flintoff        65    1  0  0  0  0  0
...              ...  ... .. .. .. .. ..
YA Abdulla       205   17  0  0  0  0  0
YK Pathan       1121   58  4  0  0  1  0
YS Chahal       1759   69  3  1  7  2  0
Yuvraj Singh     858   23  0  0  1  0  0
Z Khan          2144  118  4  0  7  3  0

[405 rows x 7 columns]

In [105]:
df_del[df_del['bowler']]['extra_runs'].max()

KeyError: "None of [Index(['TS Mills', 'TS Mills', 'TS Mills', 'TS Mills', 'TS Mills', 'TS Mills',\n       'TS Mills', 'A Choudhary', 'A Choudhary', 'A Choudhary',\n       ...\n       'JJ Bumrah', 'JJ Bumrah', 'JJ Bumrah', 'JJ Bumrah', 'SL Malinga',\n       'SL Malinga', 'SL Malinga', 'SL Malinga', 'SL Malinga', 'SL Malinga'],\n      dtype='object', length=179078)] are in the [columns]"

In [115]:
# 15. Which venue has hosted most number of IPL matches?
df_mat['venue'].value_counts()

Eden Gardens                                            77
M Chinnaswamy Stadium                                   73
Wankhede Stadium                                        73
Feroz Shah Kotla                                        67
Rajiv Gandhi International Stadium, Uppal               56
MA Chidambaram Stadium, Chepauk                         49
Sawai Mansingh Stadium                                  47
Punjab Cricket Association Stadium, Mohali              35
Maharashtra Cricket Association Stadium                 21
Subrata Roy Sahara Stadium                              17
Dr DY Patil Sports Academy                              17
Kingsmead                                               15
Punjab Cricket Association IS Bindra Stadium, Mohali    14
SuperSport Park                                         12
Sardar Patel Stadium, Motera                            12
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     11
Brabourne Stadium                                       11
Saurashtra Cricket Association Stadium                  10
Holkar Cricket Stadium                                   9
Himachal Pradesh Cricket Association Stadium             9
Rajiv Gandhi Intl. Cricket Stadium                       8
M. A. Chidambaram Stadium                                8
New Wanderers Stadium                                    8
Feroz Shah Kotla Ground                                  7
Barabati Stadium                                         7
M. Chinnaswamy Stadium                                   7
St George's Park                                         7
Newlands                                                 7
JSCA International Stadium Complex                       7
Sheikh Zayed Stadium                                     7
Dubai International Cricket Stadium                      7
IS Bindra Stadium                                        7
Shaheed Veer Narayan Singh International Stadium         6
Sharjah Cricket Stadium                                  6
Nehru Stadium                                            5
Green Park                                               4
De Beers Diamond Oval                                    3
Vidarbha Cricket Association Stadium, Jamtha             3
Buffalo Park                                             3
OUTsurance Oval                                          2
ACA-VDCA Stadium                                         2
Name: venue, dtype: int64

In [ ]:
# In 2017 when sunrisers hyderabad clashed against Royal Challengers Bangalore which team player won player of the match?

In [118]:
df_mat[(df_mat['season']=='2017') & ((df_mat['team1']=='Sunrisers Hyderabad') & (df_mat['team2']=='Royal Challengers Bangalore'))]

Empty DataFrame
Columns: [id, season, city, date, team1, team2, toss_winner, toss_decision, result, dl_applied, winner, win_by_runs, win_by_wickets, player_of_match, venue, umpire1, umpire2, umpire3]
Index: []

In [167]:
match_data = df_mat[(df_mat['season'] == 2017) &
                        (((df_mat['team1'] == 'Sunrisers Hyderabad') & (df_mat['team2'] == 'Royal Challengers Bangalore')) |
                         ((df_mat['team1'] == 'Royal Challengers Bangalore') & (df_mat['team2'] == 'Sunrisers Hyderabad')))]

In [168]:
player_of_the_match = match_data['player_of_match'].iloc[0]

In [169]:
player_of_the_match

'Yuvraj Singh'

In [123]:
df_del["dismissal_kind"].values

array([nan, nan, nan, ..., 'run out', nan, 'lbw'], dtype=object)

In [ ]:
# Across seasons who are the top three batsman's with most number of run out?
df_del['']

In [170]:
run_out_data = df_del[df_del['dismissal_kind'] == 'run out']

In [171]:
run_out_data

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
199,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,4,KM Jadhav,TM Head,MC Henriques,0,...,0,0,0,0,1,0,1,KM Jadhav,run out,BCJ Cutting
247,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,A Choudhary,YS Chahal,BCJ Cutting,0,...,0,0,0,0,0,0,0,YS Chahal,run out,CJ Jordan (sub)
371,2,1,Mumbai Indians,Rising Pune Supergiant,20,6,HH Pandya,TG Southee,AB Dinda,0,...,0,0,0,0,0,1,1,TG Southee,run out,MS Dhoni
1063,5,1,Royal Challengers Bangalore,Delhi Daredevils,17,4,Vishnu Vinod,KM Jadhav,Z Khan,0,...,0,0,0,0,0,0,0,Vishnu Vinod,run out,S Nadeem
1313,6,1,Gujarat Lions,Sunrisers Hyderabad,18,4,DS Kulkarni,P Kumar,A Nehra,0,...,0,0,0,0,0,0,0,DS Kulkarni,run out,Rashid Khan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177016,11343,1,Kings XI Punjab,Kolkata Knight Riders,14,3,Mandeep Singh,MA Agarwal,SP Narine,0,...,0,0,0,0,1,0,1,MA Agarwal,run out,R Singh
177195,11344,1,Rajasthan Royals,Delhi Capitals,5,2,SV Samson,M Lomror,AR Patel,0,...,0,0,0,0,0,0,0,SV Samson,run out,P Shaw
178951,11415,1,Mumbai Indians,Chennai Super Kings,20,4,KA Pollard,MJ McClenaghan,DJ Bravo,0,...,0,0,0,0,1,0,1,MJ McClenaghan,run out,F du Plessis
179033,11415,2,Chennai Super Kings,Mumbai Indians,13,5,SR Watson,MS Dhoni,HH Pandya,0,...,0,0,0,0,1,0,1,MS Dhoni,run out,Ishan Kishan
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya

In [172]:
run_out_counts = run_out_data['batsman'].value_counts()

In [173]:
run_out_counts

MS Dhoni       21
RG Sharma      17
KD Karthik     16
G Gambhir      15
V Kohli        15
               ..
RR Bhatkal      1
T Kohli         1
PC Valthaty     1
SP Fleming      1
J Suchith       1
Name: batsman, Length: 277, dtype: int64

In [175]:
top_3 = run_out_counts.head(3)

In [176]:
top_3

MS Dhoni      21
RG Sharma     17
KD Karthik    16
Name: batsman, dtype: int64

In [125]:
df_del['bowler'].unique()

array(['TS Mills', 'A Choudhary', 'YS Chahal', 'S Aravind', 'SR Watson',
       'TM Head', 'STR Binny', 'A Nehra', 'B Kumar', 'BCJ Cutting',
       'Rashid Khan', 'DJ Hooda', 'MC Henriques', 'Bipul Sharma',
       'AB Dinda', 'DL Chahar', 'BA Stokes', 'Imran Tahir', 'A Zampa',
       'R Bhatia', 'TG Southee', 'HH Pandya', 'MJ McClenaghan',
       'JJ Bumrah', 'KH Pandya', 'KA Pollard', 'TA Boult', 'PP Chawla',
       'SP Narine', 'CR Woakes', 'Kuldeep Yadav', 'YK Pathan', 'P Kumar',
       'DS Kulkarni', 'MS Gony', 'S Kaushik', 'DR Smith', 'SB Jakati',
       'Sandeep Sharma', 'MM Sharma', 'AR Patel', 'T Natarajan',
       'MP Stoinis', 'Swapnil Singh', 'DT Christian', 'RD Chahar',
       'Z Khan', 'CH Morris', 'PJ Cummins', 'S Nadeem', 'A Mishra',
       'CR Brathwaite', 'B Stanlake', 'Iqbal Abdulla', 'P Negi',
       'SK Raina', 'Tejas Baroka', 'Basil Thampi', 'SL Malinga',
       'Harbhajan Singh', 'AS Rajpoot', 'VR Aaron', 'CJ Anderson',
       'Mustafizur Rahman', 'UT Yadav', 'C de Grandhomme', 'I Sharma',
       'GJ Maxwell', 'S Badree', 'AJ Tye', 'RA Jadeja', 'Ankit Sharma',
       'LH Ferguson', 'SN Thakur', 'KC Cariappa', 'MM Patel', 'AF Milne',
       'JD Unadkat', 'NM Coulter-Nile', 'Mohammed Shami', 'AD Mathews',
       'BB Sran', 'S Kaul', 'Mohammad Nabi', 'J Yadav', 'Mohammed Siraj',
       'Yuvraj Singh', 'JP Faulkner', 'Shakib Al Hasan', 'K Rabada',
       'MG Johnson', 'Washington Sundar', 'SS Agarwal', 'NB Singh',
       'KV Sharma', 'RA Tripathi', 'Ankit Soni', 'Anureet Singh',
       'IK Pathan', 'PJ Sangwan', 'MN Samuels', 'MJ Henry', 'R Tewatia',
       'R Vinay Kumar', 'Avesh Khan', 'HV Patel', 'CJ Jordan',
       'AA Noffke', 'JH Kallis', 'SB Joshi', 'CL White', 'AB Agarkar',
       'SC Ganguly', 'LR Shukla', 'B Lee', 'S Sreesanth', 'JR Hopes',
       'K Goel', 'WA Mota', 'JDP Oram', 'M Muralitharan', 'P Amarnath',
       'Joginder Sharma', 'GD McGrath', 'B Geeves', 'MF Maharoof',
       'DL Vettori', 'SK Trivedi', 'SK Warne', 'D Salunkhe', 'B Akhil',
       'SM Pollock', 'ST Jayasuriya', 'AM Nayar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'WPUJC Vaas', 'RP Singh',
       'SB Styris', 'SB Bangar', 'A Symonds', 'PP Ojha', 'Pankaj Singh',
       'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi', 'DJ Bravo',
       'VS Yeligati', 'MA Khote', 'D Kalyankrishna', 'VRV Singh',
       'Sohail Tanvir', 'A Kumble', 'DNT Zoysa', 'SD Chitnis',
       'Shoaib Malik', 'DW Steyn', 'JA Morkel', 'CRD Fernando', 'V Kohli',
       'V Sehwag', 'Gagandeep Singh', 'Y Venugopal Rao', 'Umar Gul',
       'M Ntini', 'DP Vijaykumar', 'DB Ravi Teja', 'LPC Silva',
       'DJ Thornely', 'RR Raje', 'S Vidyut', 'L Balaji', 'CK Kapugedera',
       'AD Mascarenhas', 'Shoaib Akhtar', 'RR Powar', 'PM Sarvesh Kumar',
       'Abdur Razzak', 'TM Dilshan', 'RG Sharma', 'A Nel', 'BAW Mendis',
       'T Thushara', 'A Flintoff', 'Kamran Khan', 'T Henderson',
       'JD Ryder', 'DP Nannes', 'AM Salvi', 'YA Abdulla', 'VS Malik',
       'FH Edwards', 'Harmeet Singh', 'CH Gayle', 'KP Pietersen',
       'LRPL Taylor', 'RS Bopara', 'MK Tiwary', 'RR Bose', 'KP Appanna',
       'Shoaib Ahmed', 'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe',
       'JP Duminy', 'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut',
       'D du Preez', 'RJ Harris', 'TL Suman', 'A Singh', 'M Morkel',
       'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar', 'AM Rahane',
       'J Botha', 'Mashrafe Mortaza', 'AB McDonald', 'Y Nagar',
       'CK Langeveldt', 'R Ashwin', 'RA Shaikh', 'Jaskaran Singh',
       'SW Tait', 'A Uniyal', 'AA Jhunjhunwala', 'R McLaren',
       'AG Murtaza', 'R Sathish', 'RS Gavaskar', 'JM Kemp', 'S Ladda',
       'SE Bond', 'S Narwal', 'SJ Srivastava', 'AC Voges', 'R Sharma',
       'J Theron', 'NLTC Perera', 'KAJ Roach', 'PD Collingwood',
       'C Ganapathy', 'MB Parmar', 'SB Wagh', 'DE Bollinger', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'ND Doshi', 'S Randiv', 'AL Menaria', 'AUK Pathan',
       'RV Gomez', 'JEC Franklin', 'AC Thomas', 'WD Parnell', 'M Manhas',
       'NJ Rimmington', 'RN ten Doeschate', 'BA Bhatt', 'JJ van der Wath',
       'R Ninan', 'PC Valthaty', 'S Dhawan', 'J Syed Mohammad',
       'NL McCullum', 'JE Taylor', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'AA Kazi', 'Anand Rajan', 'P Prasanth',
       'Y Gnaneswara Rao', 'AA Chavan', 'S Rana', 'SS Mundhe', 'RW Price',
       'M de Lange', 'KK Cooper', 'DAJ Bracewell', 'DJ Harris',
       'TP Sudhindra', 'F du Plessis', 'GB Hogg', 'RR Bhatkal', 'P Awana',
       'V Pratap Singh', 'CJ McKay', 'AD Russell', 'A Ashish Reddy',
       'Azhar Mahmood', 'A Chandila', 'LJ Wright', 'RJ Peterson',
       'R Shukla', 'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith',
       'K Upadhyay', 'Sunny Gupta', 'B Laughlin', 'GH Vihari',
       'BMAJ Mendis', 'Harmeet Singh (2)', 'R Dhawan', 'R Rampaul',
       'SMSM Senanayake', 'JO Holder', 'IC Pandey', 'DJG Sammy',
       'KW Richardson', 'P Suyal', 'PV Tambe', 'BJ Rohrer',
       'Parvez Rasool', 'MG Neser', 'AC Gilchrist', 'MA Starc',
       'JDS Neesham', 'M Vijay', 'SA Yadav', 'Shivam Sharma', 'V Shankar',
       'LMP Simmons', 'K Santokie', 'S Gopal', 'BE Hendricks',
       'JW Hastings', 'Karanveer Singh', 'DJ Muthuswami', 'SA Abbott',
       'J Suchith', 'RG More', 'D Wiese', 'GS Sandhu', 'Gurkeerat Singh',
       'M Ashwin', 'C Munro', 'P Sahu', 'KJ Abbott', 'T Shamsi',
       'SM Boland', 'Sachin Baby', 'N Rana', 'KS Williamson', 'M Wood',
       'M Markande', 'M Ur Rahman', 'K Khejroliya', 'K Gowtham',
       'D Short', 'T Curran', 'A Dananjaya', 'S Mavi', 'J Archer',
       'L Plunkett', 'I Sodhi', 'M Lomror', 'L Ngidi', 'KM Asif',
       'D Willey', 'P Krishna', 'M Ali', 'J Searles', 'S Lamichhane',
       'J Dala', 'K Ahmed', 'N Saini', 'S Dube', 'L Ferguson', 'S Sharma',
       'R Salam', 'K Paul', 'S Curran', 'V Chakravarthy', 'H Viljoen',
       'Mandeep Singh', 'P R Barman', 'M Santner', 'H Vihari',
       'J Behrendorff', 'S Kuggeleijn', 'A Joseph', 'H Gurney',
       'S Midhun', 'R Parag', 'L Livingstone', 'SN Khan', 'S Rutherford',
       'H Brar', 'P Raj', 'O Thomas', 'A Roy', 'S Warrier'], dtype=object)

In [126]:
df_del.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [129]:
#  What are the total runs scored by V Kohli when the bowler was JJ Burmah?
df_del[(df_del['batsman']=='V Kohli') & (df_del['bowler']=='JJ Bumrah')]['total_runs'].sum()

114

In [177]:
# Across all seasons which player was dismissed the maximum number of times via caught and bowled

cau_bow = df_del[df_del['dismissal_kind'] == 'caught and bowled']

In [178]:
caught_bowled_counts = cau_bow['batsman'].value_counts()

In [179]:
caught_bowled_counts

SK Raina      7
RG Sharma     6
AT Rayudu     5
RA Jadeja     5
R Dravid      5
             ..
AB Agarkar    1
ML Hayden     1
IK Pathan     1
MK Tiwary     1
JC Buttler    1
Name: batsman, Length: 120, dtype: int64